- name: init cluster
  shell: kubeadm init --v=5 >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt


- name: network plugin installation(living on edge)
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"