- name: Add the br_netfilter module
  modprobe:
    name: br_netfilter
    state: present


- name: enable bridge
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

  
- name:  enable bridge
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes


- name: Install dependencies
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    update_cache: yes

- name: google cert
  shell: sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: apt repo
  shell: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list


- name: Install kube*
  apt:
    pkg:
    - kubelet 
    - kubeadm 
    - kubectl
    update_cache: yes