- hosts: all
  become: yes
  roles:
  - { role: roles/common }
  - { role: roles/docker }


- hosts: master-nodes
  become: yes
  roles:
  - { role: roles/master }

- hosts: master-nodes
  become: yes
  tasks:
  - name: get join command
    shell: kubeadm token create --print-join-command
    register: join_command_raw

  - name: set join command
    set_fact:
      join_command: "{{ join_command_raw.stdout_lines[0] }}"

  - name: Prints two lines of messages, but only if there is an environment value set
  ansible.builtin.debug:
   msg:
   - "Provisioning based on YOUR_KEY which is: {{ join_command }}"


- hosts: worker-nodes
  become: yes
  tasks: 

  - name: join cluster
    shell: "{{ hostvars[groups['master-nodes'][0]]['join_command'] }} >> node_joined.txt"
    args:
      chdir: $HOME
      creates: node_joined.txt  